### ISSUE TITLE
アプリURLのバグ

### ISSUE THREAD

**Issue by on-keyday** [cp-20/2024.cp20.dev#5]
ふらっと見ていたらバグとおもわれる挙動を見つけてしまったので報告しておきます。
作品一覧の記事にアクセスした後
下の遷移ボタンを押して移動したあと移動先の「アプリURL」部分
をクリックするとなぜか前のページの「アプリURL」のリンク先に飛ぶ状態になっています。
(例: https://cp20.dev/works/c-compiler/ -> 下の「cp20.dev (2024)」を押す(https://cp20.dev/works/2024-portfolio/ に遷移) -> アプリURL(表示: https://cp20.dev )を押す -> https://github.com/cp-20/c-compiler に飛ぶ)

**Comment by cp-20** [comment]
わ、本当ですね　バグ報告ありがとうございます:bow:　ただもしかしたらQwikのバグかもしれません (もう少し調査が必要そうです)
